// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBlogStmt, err = db.PrepareContext(ctx, createBlog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBlog: %w", err)
	}
	if q.createChildStmt, err = db.PrepareContext(ctx, createChild); err != nil {
		return nil, fmt.Errorf("error preparing query CreateChild: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteBlogStmt, err = db.PrepareContext(ctx, deleteBlog); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBlog: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getBlogbyIdStmt, err = db.PrepareContext(ctx, getBlogbyId); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlogbyId: %w", err)
	}
	if q.getChildByIDStmt, err = db.PrepareContext(ctx, getChildByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetChildByID: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.listBlogsStmt, err = db.PrepareContext(ctx, listBlogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListBlogs: %w", err)
	}
	if q.listChildrenStmt, err = db.PrepareContext(ctx, listChildren); err != nil {
		return nil, fmt.Errorf("error preparing query ListChildren: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.updateBlogStmt, err = db.PrepareContext(ctx, updateBlog); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBlog: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBlogStmt != nil {
		if cerr := q.createBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBlogStmt: %w", cerr)
		}
	}
	if q.createChildStmt != nil {
		if cerr := q.createChildStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChildStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteBlogStmt != nil {
		if cerr := q.deleteBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBlogStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getBlogbyIdStmt != nil {
		if cerr := q.getBlogbyIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlogbyIdStmt: %w", cerr)
		}
	}
	if q.getChildByIDStmt != nil {
		if cerr := q.getChildByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChildByIDStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.listBlogsStmt != nil {
		if cerr := q.listBlogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBlogsStmt: %w", cerr)
		}
	}
	if q.listChildrenStmt != nil {
		if cerr := q.listChildrenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listChildrenStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.updateBlogStmt != nil {
		if cerr := q.updateBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBlogStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	createBlogStmt        *sql.Stmt
	createChildStmt       *sql.Stmt
	createUserStmt        *sql.Stmt
	deleteBlogStmt        *sql.Stmt
	deleteUserStmt        *sql.Stmt
	getBlogbyIdStmt       *sql.Stmt
	getChildByIDStmt      *sql.Stmt
	getUserByIDStmt       *sql.Stmt
	getUserByUsernameStmt *sql.Stmt
	listBlogsStmt         *sql.Stmt
	listChildrenStmt      *sql.Stmt
	listUsersStmt         *sql.Stmt
	updateBlogStmt        *sql.Stmt
	updateUserStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		createBlogStmt:        q.createBlogStmt,
		createChildStmt:       q.createChildStmt,
		createUserStmt:        q.createUserStmt,
		deleteBlogStmt:        q.deleteBlogStmt,
		deleteUserStmt:        q.deleteUserStmt,
		getBlogbyIdStmt:       q.getBlogbyIdStmt,
		getChildByIDStmt:      q.getChildByIDStmt,
		getUserByIDStmt:       q.getUserByIDStmt,
		getUserByUsernameStmt: q.getUserByUsernameStmt,
		listBlogsStmt:         q.listBlogsStmt,
		listChildrenStmt:      q.listChildrenStmt,
		listUsersStmt:         q.listUsersStmt,
		updateBlogStmt:        q.updateBlogStmt,
		updateUserStmt:        q.updateUserStmt,
	}
}
