// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (title, content, user_id, created, updated)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING id, title, content, user_id, created, updated
`

type CreateBlogParams struct {
	Title   string        `json:"title"`
	Content string        `json:"content"`
	UserID  sql.NullInt32 `json:"user_id"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.createBlogStmt, createBlog, arg.Title, arg.Content, arg.UserID)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createChild = `-- name: CreateChild :one
INSERT INTO children (username, email, password, parent_id, created, updated)
VALUES ($1, $2, $3, $4,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING id, username, email, parent_id, created, updated
`

type CreateChildParams struct {
	Username string        `json:"username"`
	Email    string        `json:"email"`
	Password string        `json:"password"`
	ParentID sql.NullInt32 `json:"parent_id"`
}

type CreateChildRow struct {
	ID       int32         `json:"id"`
	Username string        `json:"username"`
	Email    string        `json:"email"`
	ParentID sql.NullInt32 `json:"parent_id"`
	Created  sql.NullTime  `json:"created"`
	Updated  sql.NullTime  `json:"updated"`
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) (CreateChildRow, error) {
	row := q.queryRow(ctx, q.createChildStmt, createChild,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.ParentID,
	)
	var i CreateChildRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.ParentID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password, created, updated)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING id, username, email, created, updated
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :one
DELETE FROM blogs
WHERE id = $1
RETURNING id, title, content, user_id, created, updated
`

func (q *Queries) DeleteBlog(ctx context.Context, id int32) (Blog, error) {
	row := q.queryRow(ctx, q.deleteBlogStmt, deleteBlog, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteChild = `-- name: DeleteChild :one
DELETE FROM children
WHERE id = $1
RETURNING id, username, email, parent_id, password, created, updated
`

func (q *Queries) DeleteChild(ctx context.Context, id int32) (Child, error) {
	row := q.queryRow(ctx, q.deleteChildStmt, deleteChild, id)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.ParentID,
		&i.Password,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, username, email, password, created, updated
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (User, error) {
	row := q.queryRow(ctx, q.deleteUserStmt, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getBlogbyId = `-- name: GetBlogbyId :one
SELECT id, title, content, user_id, created, updated
FROM blogs
WHERE id = $1
`

func (q *Queries) GetBlogbyId(ctx context.Context, id int32) (Blog, error) {
	row := q.queryRow(ctx, q.getBlogbyIdStmt, getBlogbyId, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getChildByID = `-- name: GetChildByID :one
SELECT id, username, email, parent_id, created, updated
FROM children
WHERE id = $1
`

type GetChildByIDRow struct {
	ID       int32         `json:"id"`
	Username string        `json:"username"`
	Email    string        `json:"email"`
	ParentID sql.NullInt32 `json:"parent_id"`
	Created  sql.NullTime  `json:"created"`
	Updated  sql.NullTime  `json:"updated"`
}

func (q *Queries) GetChildByID(ctx context.Context, id int32) (GetChildByIDRow, error) {
	row := q.queryRow(ctx, q.getChildByIDStmt, getChildByID, id)
	var i GetChildByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.ParentID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, created, updated
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, created, updated
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, title, content, user_id, created, updated
FROM blogs
ORDER BY id
`

func (q *Queries) ListBlogs(ctx context.Context) ([]Blog, error) {
	rows, err := q.query(ctx, q.listBlogsStmt, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildren = `-- name: ListChildren :many
SELECT id, username, email, parent_id, created, updated
FROM children
ORDER BY id
`

type ListChildrenRow struct {
	ID       int32         `json:"id"`
	Username string        `json:"username"`
	Email    string        `json:"email"`
	ParentID sql.NullInt32 `json:"parent_id"`
	Created  sql.NullTime  `json:"created"`
	Updated  sql.NullTime  `json:"updated"`
}

func (q *Queries) ListChildren(ctx context.Context) ([]ListChildrenRow, error) {
	rows, err := q.query(ctx, q.listChildrenStmt, listChildren)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildrenRow{}
	for rows.Next() {
		var i ListChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.ParentID,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, created, updated
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs
    SET title = $2,
    content = $3
WHERE id = $1
RETURNING id, title, content, user_id, created, updated
`

type UpdateBlogParams struct {
	ID      int32  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.updateBlogStmt, updateBlog, arg.ID, arg.Title, arg.Content)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateChild = `-- name: UpdateChild :one
UPDATE children
    SET username = $2,
    email = $3
WHERE id = $1
RETURNING id, username, email, parent_id, password, created, updated
`

type UpdateChildParams struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateChild(ctx context.Context, arg UpdateChildParams) (Child, error) {
	row := q.queryRow(ctx, q.updateChildStmt, updateChild, arg.ID, arg.Username, arg.Email)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.ParentID,
		&i.Password,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
    SET username = $2,
    email = $3
WHERE id = $1
RETURNING id, username, email, password, created, updated
`

type UpdateUserParams struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser, arg.ID, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
